# Generated by Django 5.0.2 on 2024-02-25 11:56

import django.contrib.auth.models
import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itsname', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=255)),
                ('gender', models.CharField(default='ss', max_length=255)),
                ('age', models.IntegerField(default=12)),
                ('img2', models.CharField(default='ebe', max_length=255)),
                ('img3', models.CharField(default='ee', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, max_length=10), default=[-1], size=8)),
                ('board2', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, max_length=10), default=[-1], size=8)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itsname', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=255)),
                ('gender', models.CharField(default='ss', max_length=255)),
                ('age', models.IntegerField(default=12)),
                ('img2', models.CharField(default='ebe', max_length=255)),
                ('img3', models.CharField(default='ee', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itsname', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=255)),
                ('gender', models.CharField(default='ss', max_length=255)),
                ('age', models.IntegerField(default=12)),
                ('img2', models.CharField(default='ebe', max_length=255)),
                ('img3', models.CharField(default='ee', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='s', max_length=255, unique=True)),
                ('password', models.CharField(default='s', max_length=255)),
                ('email', models.CharField(default='s', max_length=255)),
                ('last_login', models.CharField(default='s', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
