# Generated by Django 5.0.2 on 2024-02-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypay', '0002_alter_personal_cart_board2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_cart',
            name='board2',
        ),
    ]
