from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.hi, name='hi'),
    path('hi', views.hi, name='hi'),
    path('register_user', views.register_user, name='register_user'),
    path('login_user', views.login_user, name="login_user"),
    path('logout_user',views.logout_user, name="logout_user"),
    path('age0_3', views.age0_3, name="age0_3"),
    path('age4_9', views.age4_9, name="age4_9"),
    path('age10_14', views.age10_14, name="age10_14"),
    path('age14plus', views.age14plus, name="age14plus"),
    path('log0_3', views.log0_3, name="log0_3"),
    path('log4_9', views.log4_9, name="log4_9"),
    path('log10_14', views.log10_14, name="log10_14"),
    path('log14plus', views.log14plus, name="log14plus"),
    path('girll', views.girll, name="girll"),
    path('boy', views.boy, name="boy"),
    path('girl', views.girl, name="girl"),
    path('boyl', views.boyl, name="boyl"),
    path('hi2', views.hi2, name="hi2"),
    path('hi2id/<int:id>', views.hi2id, name="hi2id"),
    path('cart/<int:id>', views.cart, name="cart"),
    path('details/<int:id>', views.details, name='details'),
    path('details/login_user', views.login_user, name='login'),
    path('details/details/<int:id>', views.details, name='detailss'),
    path('details/details/details/<int:id>', views.details, name='detailsss'),
    path('details/details/details/details/<int:id>', views.details, name='detailssss'),
    path('details/details/details/details/details/<int:id>', views.details, name='detailsssss'),
    path('details/details/details/details/details/details<int:id>', views.details, name='detailssssss'),
    path('details2/<int:id>', views.details2, name='details2'),
    path('details2/details2/<int:id>', views.details2, name='detailss2'),
    path('details2/details2/details2/<int:id>', views.details2, name='detailsss2'),
    path('details2/details2/details2/details2/<int:id>', views.details2, name='detailssss2'),
    path('details2/details2/details2/details2/details2/<int:id>', views.details2, name='detailsssss2'),
    path('details2/details2/details2/details2/details2/details2<int:id>', views.details2, name='detailssssss2'),
]
